image: python:3.6-slim

before_script:
- python -V
- apt-get update -q -y # quiet and automatically assume yes
- pip install -r requirements.txt


stages:
- test

test_job:
  stage: test
  script:
  - echo "Running tests"
  - python -m unittest discover -s "./tests/"