image: python:3.6-slim

before_script:
- python -V
- apt-get update -q -y # Quiet and automatically assume yes
- apt-get install libgl1-mesa-glx -y # Allow ModernGL to work
- pip install -r requirements.txt
- pip install twine

stages:
- test
- build
- deploy

test_job:
  stage: test
  script:
  - echo "Running tests"
  - python -m unittest discover -s "./tests/"
  
build_job:
  stage: build
  script:
  - echo "Build package with setup.py"
  - python setup.py sdist
  artifacts:
    paths:
      - dist/
  
deploy_staging_job:
  stage: deploy
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_PASSWORD
  script:
    - echo "Deploy for staging"
    - twine upload --repository-url $STAGING_URL dist/*
  only:
    - tags